// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Api.Persistence.Contexts;

#nullable disable

namespace Project.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208093400_AddBookFakerv2")]
    partial class AddBookFakerv2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project.Api.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Author");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Discount")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019c3c99-d3d4-70b5-bb69-6052de365d79"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 147, DateTimeKind.Utc).AddTicks(9812),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Qui labore asperiores alias iure dignissimos quisquam ratione",
                            Price = 25.28m,
                            ReleaseDate = new DateTime(2025, 6, 2, 9, 34, 0, 152, DateTimeKind.Utc).AddTicks(8746),
                            Stock = 43
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-71f6-8a7f-95c63ebd651a"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(4637),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Voluptatem at labore at nesciunt libero quo soluta",
                            Price = 2.12m,
                            ReleaseDate = new DateTime(2025, 12, 16, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5105),
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7211-b56f-fb78b5b4841c"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5127),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Molestiae quod minima et est dolor nostrum",
                            Price = 31.17m,
                            ReleaseDate = new DateTime(2025, 7, 2, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5231),
                            Stock = 127
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-70cd-9214-4e7556bc4866"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5239),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Et voluptatibus eos ad autem iure",
                            Price = 11.29m,
                            ReleaseDate = new DateTime(2025, 11, 28, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5289),
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7c45-b26a-feb2831ccfa5"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5294),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Ut molestiae cupiditate",
                            Price = 28.79m,
                            ReleaseDate = new DateTime(2025, 7, 26, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5323),
                            Stock = 98
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7983-b0c8-0401f6d0edf6"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5326),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "At ipsam esse quia eaque",
                            Price = 44.50m,
                            ReleaseDate = new DateTime(2025, 4, 24, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5361),
                            Stock = 39
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7df2-91a1-2202cdc18dcb"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5414),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Est veniam nemo",
                            Price = 34.50m,
                            ReleaseDate = new DateTime(2025, 9, 30, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5437),
                            Stock = 58
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7b9e-94ac-97da1adfef62"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5440),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Est itaque quae non",
                            Price = 12.22m,
                            ReleaseDate = new DateTime(2025, 9, 2, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5467),
                            Stock = 49
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7d50-a9cd-805a21f27f96"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5469),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Est ex ut maxime laborum et",
                            Price = 19.18m,
                            ReleaseDate = new DateTime(2026, 2, 5, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5504),
                            Stock = 108
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-76ee-87df-b8728a707dbf"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5506),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Ut cum et incidunt deserunt totam",
                            Price = 24.01m,
                            ReleaseDate = new DateTime(2025, 10, 28, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5543),
                            Stock = 86
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7c58-9b95-ab1589b94afc"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5546),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Voluptates ex dolor asperiores sequi vero",
                            Price = 38.90m,
                            ReleaseDate = new DateTime(2026, 1, 30, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5573),
                            Stock = 138
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-775c-a3d7-55a7ec5f9ab7"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5575),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Voluptate animi aut impedit cum totam vel",
                            Price = 31.09m,
                            ReleaseDate = new DateTime(2026, 1, 26, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5609),
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-750c-abd3-878339d77a46"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5611),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Optio qui aperiam voluptatem et perspiciatis qui et",
                            Price = 20.23m,
                            ReleaseDate = new DateTime(2025, 7, 17, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5655),
                            Stock = 93
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7075-ab7a-b7b26555140b"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5657),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Ut laudantium autem sed qui rerum",
                            Price = 6.10m,
                            ReleaseDate = new DateTime(2025, 6, 7, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5721),
                            Stock = 147
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-78bf-a0b4-2874ef0b6f73"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5724),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "In qui omnis dolores vel est nemo",
                            Price = 24.75m,
                            ReleaseDate = new DateTime(2025, 8, 21, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5754),
                            Stock = 109
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7822-9ad6-c6c2d0221d21"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5757),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Eaque error sed inventore",
                            Price = 40.12m,
                            ReleaseDate = new DateTime(2025, 12, 25, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5785),
                            Stock = 106
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-707f-9278-78802f9f06a9"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5788),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Dolorem qui facilis autem",
                            Price = 11.84m,
                            ReleaseDate = new DateTime(2025, 6, 14, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5811),
                            Stock = 104
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7650-8969-fb03b2bcc806"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5814),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Ab eaque distinctio ut ea placeat voluptatum occaecati",
                            Price = 35.02m,
                            ReleaseDate = new DateTime(2025, 8, 24, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5850),
                            Stock = 147
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-7033-b12b-3b84472bff28"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5853),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Et enim quasi",
                            Price = 6.17m,
                            ReleaseDate = new DateTime(2025, 4, 12, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5869),
                            Stock = 33
                        },
                        new
                        {
                            Id = new Guid("019c3c99-d3d9-76a9-8be6-e89a3ced0298"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5872),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Quam quis ut minima consequuntur et",
                            Price = 41.26m,
                            ReleaseDate = new DateTime(2025, 9, 11, 9, 34, 0, 153, DateTimeKind.Utc).AddTicks(5902),
                            Stock = 85
                        });
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookAuthor", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookAuthors");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookLanguage", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("BookId", "LanguageId");

                    b.ToTable("BooksLanguages");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookSeller", b =>
                {
                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.HasKey("SellerId", "BookId");

                    b.HasIndex("BookId", "SellerId");

                    b.ToTable("BookSellers");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.CategoryBook", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BookId", "CategoryId");

                    b.ToTable("CategoryBook");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("DiscountPercentage")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Metrics.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("MeasuredAt");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.Property<string>("Surname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookAuthor", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookLanguage", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("Languages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookSeller", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("BookSellers")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Category", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.CategoryBook", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("CategoryBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Order", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Book", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("BookSellers");

                    b.Navigation("CategoryBooks");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
