// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Api.Persistence.Contexts;

#nullable disable

namespace Project.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208091910_AddBookFaker")]
    partial class AddBookFaker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project.Api.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Author");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Discount")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019c3c8c-3d68-7e8d-b317-46a1f30cdbe3"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 19, 9, 671, DateTimeKind.Utc).AddTicks(2701),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Voluptatem atque odit",
                            Price = 10.91m,
                            ReleaseDate = new DateTime(2025, 2, 25, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(3918),
                            Stock = 102
                        },
                        new
                        {
                            Id = new Guid("019c3c8c-3d6c-791a-9d70-138551143e6e"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9390),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Iusto deserunt ea quam",
                            Price = 16.77m,
                            ReleaseDate = new DateTime(2025, 3, 26, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9676),
                            Stock = 98
                        },
                        new
                        {
                            Id = new Guid("019c3c8c-3d6c-76d8-a099-ff6ef931f180"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9691),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "In ab est animi",
                            Price = 28.60m,
                            ReleaseDate = new DateTime(2025, 8, 4, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9745),
                            Stock = 44
                        },
                        new
                        {
                            Id = new Guid("019c3c8c-3d6c-7ca0-9f7e-ddff83b24da0"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9752),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Voluptas aut eligendi et sint molestiae exercitationem",
                            Price = 10.30m,
                            ReleaseDate = new DateTime(2025, 9, 18, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9856),
                            Stock = 123
                        },
                        new
                        {
                            Id = new Guid("019c3c8c-3d6c-71d3-b2b0-be4f433edb79"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9859),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Ut tempora repudiandae",
                            Price = 3.42m,
                            ReleaseDate = new DateTime(2025, 8, 1, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9892),
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("019c3c8c-3d6c-7516-bb0e-e08fdaad6797"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9896),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Maiores voluptas sint omnis fuga ut at",
                            Price = 6.45m,
                            ReleaseDate = new DateTime(2025, 6, 3, 9, 19, 9, 676, DateTimeKind.Utc).AddTicks(9943),
                            Stock = 17
                        });
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookAuthor", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookAuthors");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookLanguage", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("BookId", "LanguageId");

                    b.ToTable("BooksLanguages");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookSeller", b =>
                {
                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.HasKey("SellerId", "BookId");

                    b.HasIndex("BookId", "SellerId");

                    b.ToTable("BookSellers");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.CategoryBook", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BookId", "CategoryId");

                    b.ToTable("CategoryBook");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("DiscountPercentage")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Metrics.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("MeasuredAt");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.Property<string>("Surname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookAuthor", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookLanguage", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("Languages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookSeller", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("BookSellers")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Category", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.CategoryBook", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("CategoryBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Order", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Book", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("BookSellers");

                    b.Navigation("CategoryBooks");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
