// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Api.Persistence.Contexts;

#nullable disable

namespace Project.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208093547_AddBookFakerv3")]
    partial class AddBookFakerv3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project.Api.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Author");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Discount")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019c3c9b-7675-7855-a1bd-c4da7e20509d"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 35, 47, 316, DateTimeKind.Utc).AddTicks(7349),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Quia dolorem et quae maiores provident voluptatem similique",
                            Price = 16.50m,
                            ReleaseDate = new DateTime(2025, 9, 15, 9, 35, 47, 322, DateTimeKind.Utc).AddTicks(2733),
                            Stock = 89
                        },
                        new
                        {
                            Id = new Guid("019c3c9b-767b-7b2f-a03f-21e2c50c9b8f"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(243),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Assumenda dolorum et asperiores aut rerum",
                            Price = 48.60m,
                            ReleaseDate = new DateTime(2025, 4, 1, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(887),
                            Stock = 56
                        },
                        new
                        {
                            Id = new Guid("019c3c9b-767b-7c0b-8a1e-bd1fa208959a"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(903),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Est consectetur recusandae ipsam omnis",
                            Price = 5.04m,
                            ReleaseDate = new DateTime(2025, 8, 24, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(959),
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("019c3c9b-767b-7717-a3cd-a8b01c232f5b"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(966),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Quae quod et",
                            Price = 16.57m,
                            ReleaseDate = new DateTime(2025, 3, 13, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(994),
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("019c3c9b-767b-72f0-971c-5a3bb9763d8b"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(997),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Molestiae voluptatem fuga soluta quidem",
                            Price = 35.85m,
                            ReleaseDate = new DateTime(2025, 5, 30, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(1030),
                            Stock = 81
                        },
                        new
                        {
                            Id = new Guid("019c3c9b-767b-7db7-8245-f82acb7c6a32"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(1033),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Quod molestiae et omnis id consequatur quasi",
                            Price = 11.91m,
                            ReleaseDate = new DateTime(2025, 2, 18, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(1120),
                            Stock = 59
                        },
                        new
                        {
                            Id = new Guid("019c3c9b-767b-74f3-bbcf-7fb0affdfbe8"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(1124),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Voluptas et natus magnam et pariatur dicta repellat",
                            Price = 30.94m,
                            ReleaseDate = new DateTime(2025, 10, 22, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(1166),
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("019c3c9b-767b-7ac1-8d0c-96a4abbda4c2"),
                            CreatedAt = new DateTime(2026, 2, 8, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(1169),
                            Discount = (byte)0,
                            IsDeleted = false,
                            IsReleased = false,
                            Name = "Accusantium repellat aut distinctio nihil magni",
                            Price = 5.11m,
                            ReleaseDate = new DateTime(2025, 4, 28, 9, 35, 47, 323, DateTimeKind.Utc).AddTicks(1201),
                            Stock = 87
                        });
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookAuthor", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookAuthors");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookLanguage", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("BookId", "LanguageId");

                    b.ToTable("BooksLanguages");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookSeller", b =>
                {
                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.HasKey("SellerId", "BookId");

                    b.HasIndex("BookId", "SellerId");

                    b.ToTable("BookSellers");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.CategoryBook", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BookId", "CategoryId");

                    b.ToTable("CategoryBook");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("DiscountPercentage")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Metrics.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("MeasuredAt");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.Property<string>("Surname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookAuthor", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookLanguage", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("Languages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.BookSeller", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("BookSellers")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Category", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.CategoryBook", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.Book", "Book")
                        .WithMany("CategoryBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Api.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Order", b =>
                {
                    b.HasOne("Project.Api.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Book", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("BookSellers");

                    b.Navigation("CategoryBooks");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Project.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
