global using MediatR;
global using Carter;
global using Application.CQRS.Books.DTOs;
global using Application.CQRS.Auth.DTOs;
global using Application.CQRS.Categories.DTOs;
global using Application.CQRS.Coupons.DTOs;
global using Application.CQRS.Orders.DTOs;
global using Persistence.Data;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.AspNetCore.Http;
global using Application.Services.Abstractions;
global using Application.Services.Implementations;
global using Domain.Models;
global using ArgumentException = Domain.Exceptions.ArgumentException;
global using BadRequestException = Domain.Exceptions.BadRequestException;
global using DbUpdateException = Domain.Exceptions.DbUpdateException;
global using InvalidDataException = Domain.Exceptions.InvalidDataException;
global using NotFoundException = Domain.Exceptions.NotFoundException;
global using NullReferenceException = Domain.Exceptions.NullReferenceException;
global using Domain.Exceptions.BaseException;
global using Persistence.UnitOfWorks;
global using Infrastructure.Providers.Tokens;
global using Infrastructure.Providers.Coupons;
global using Microsoft.Extensions.Caching.Memory;
global using FluentValidation;
global using System.Security.Claims;
global using System.Text.Json;
